Repository osrf/gazebo, pull requests merged in 2020-08, with the labels that each got.

#2800 ⬆️ 7.16.1
  CMakeLists.txt
  Changelog.md
Labels: 7

#2797 Fix pkg-config boost entries for Ubuntu Focal (gazebo11)
  CMakeLists.txt
  Changelog.md
Labels: 11

#2801 7 ➡️ 9
  Changelog.md
  doc/mainpage.html
Labels: 9

#2812 Fix race condition on Publisher shutdown
  gazebo/transport/Publisher.cc
  gazebo/transport/Publisher.hh
Labels: 9

#2815 ⬆️ 9.14.0
  CMakeLists.txt
  Changelog.md
Labels: 9

#2789 [Gazebo9] More enhancement for Windows build
  cmake/GazeboUtils.cmake
  gazebo/common/Material.cc
  gazebo/common/ModelDatabase.cc
Labels: 9

#2809 [Gazebo9] Fixed fails for OSX: Added using namespace boost::placeholders
  examples/stand_alone/custom_main_pkgconfig/CMakeLists.txt
  gazebo/gui/model/ModelTreeWidget.cc
  gazebo/gui/model/SchematicViewWidget.cc
  test/plugins/ForceTorqueModelRemovalTestPlugin.cc
Labels: 9

#2811 This fix for cases where VERTEX and NROMAL share same polylist <p> , see https://github.com/osrf/gazebo/issues/2682#issue-602951524
  gazebo/common/ColladaLoader.cc
  test/integration/collada_visualization.cc
  test/integration/collada_visualization.hh
  test/media/models/box-assimp-3.dae
  test/media/models/box-assimp-4.dae
  test/worlds/multiple_input_with_same_offset_test.world
Labels: 11

#2816 gazebo10 -> gazebo11 forward port
  Changelog.md
  Migration.md
  cmake/GazeboTestUtils.cmake
  cmake/GazeboUtils.cmake
  examples/plugins/gui_overlay_plugin_spawn/CMakeLists.txt
  examples/plugins/gui_overlay_plugin_spawn/GUIExampleSpawnWidget.hh
  examples/plugins/gui_overlay_plugin_time/CMakeLists.txt
  examples/plugins/gui_overlay_plugin_time/GUIExampleTimeWidget.hh
  examples/plugins/mainwindow_example/CMakeLists.txt
  examples/plugins/mainwindow_example/MainWindowExampleWidget.hh
  examples/plugins/movable_text_demo/CMakeLists.txt
  examples/stand_alone/custom_main_pkgconfig/CMakeLists.txt
  gazebo/gui/GuiIface.cc
  gazebo/gui/model/ModelTreeWidget.cc
  gazebo/gui/model/SchematicViewWidget.cc
  gazebo/gui/qtpropertybrowser/CMakeLists.txt
  gazebo/msgs/CMakeLists.txt
  gazebo/physics/HeightmapShape.hh
  gazebo/rendering/DepthCamera.cc
  gazebo/rendering/DepthCamera.hh
  gazebo/rendering/DepthCameraPrivate.hh
  gazebo/rendering/LensFlare.cc
  gazebo/rendering/Visual.cc
  gazebo/sensors/DepthCameraSensor.cc
  gazebo/sensors/DepthCameraSensor_TEST.cc
  gazebo/sensors/SensorManager.cc
  media/materials/scripts/gazebo.material
  plugins/CMakeLists.txt
  plugins/DepthCameraPlugin.cc
  plugins/DepthCameraPlugin.hh
  plugins/ReflectancePlugin.cc
  plugins/ReflectancePlugin.hh
  test/integration/joint_spawn.cc
  test/integration/sensor.cc
  test/plugins/ForceTorqueModelRemovalTestPlugin.cc
  tools/gz_TEST.cc
  worlds/reflectance.world
Labels: 11

#2826 👩‍🌾 Fixed fails for OSX: Added using namespace boost::placeholders
  examples/stand_alone/custom_main_pkgconfig/CMakeLists.txt
  gazebo/gui/model/ModelTreeWidget.cc
  gazebo/gui/model/SchematicViewWidget.cc
  test/plugins/ForceTorqueModelRemovalTestPlugin.cc
Labels: bug, os::osx

#2778 Fix assumptions that CMAKE_INSTALL_*DIR paths are relative.
  CMakeLists.txt
  cmake/JoinPaths.cmake
  cmake/gazebo-config.cmake.in
  cmake/pkgconfig/gazebo.in
  cmake/pkgconfig/gazebo_ode.in
  cmake/pkgconfig/gazebo_transport.in
Labels: 11

#2779 [gazebo9] Fix assumptions that CMAKE_INSTALL_*DIR paths are relative.
  CMakeLists.txt
  cmake/JoinPaths.cmake
  cmake/gazebo-config.cmake.in
  cmake/pkgconfig/gazebo.in
  cmake/pkgconfig/gazebo_ode.in
  cmake/pkgconfig/gazebo_transport.in
  plugins/CMakeLists.txt
Labels: 9

#2780 [gazebo7] Fix assumptions that CMAKE_INSTALL_*DIR paths are relative.
  CMakeLists.txt
  cmake/JoinPaths.cmake
  cmake/gazebo-config.cmake.in
  cmake/pkgconfig/gazebo.in
  cmake/pkgconfig/gazebo_ode.in
  cmake/pkgconfig/gazebo_transport.in
  plugins/CMakeLists.txt
Labels: 7
