Repository osrf/gazebo, pull requests merged in 2020-10, with the labels that each got.

#2850 ⬆️ 9.15.0
  CMakeLists.txt
  Changelog.md
Labels: 9

#2851 ⬆️ 11.2.0
  CMakeLists.txt
  Changelog.md
Labels: 11

#2837 [Gazebo 11] Added profiler to gazebo::rendering
  gazebo/gui/GLWidget.cc
  gazebo/gui/GuiIface.cc
  gazebo/gui/main.cc
  gazebo/rendering/ApplyWrenchVisual.cc
  gazebo/rendering/Camera.cc
  gazebo/rendering/CameraVisual.cc
  gazebo/rendering/ContactVisual.cc
  gazebo/rendering/DynamicLines.cc
  gazebo/rendering/FPSViewController.cc
  gazebo/rendering/GpuLaser.cc
  gazebo/rendering/LaserVisual.cc
  gazebo/rendering/LensFlare.cc
  gazebo/rendering/Light.cc
  gazebo/rendering/MarkerVisual.cc
  gazebo/rendering/Material.cc
  gazebo/rendering/MovableText.cc
  gazebo/rendering/OculusCamera.cc
  gazebo/rendering/RTShaderSystem.cc
  gazebo/rendering/RenderEngine.cc
  gazebo/rendering/Scene.cc
  gazebo/rendering/SonarVisual.cc
  gazebo/rendering/TransmitterVisual.cc
  gazebo/rendering/UserCamera.cc
  gazebo/rendering/VideoVisual.cc
  gazebo/rendering/Visual.cc
  gazebo/rendering/WrenchVisual.cc
  gazebo/rendering/skyx/src/CloudsManager.cpp
  gazebo/rendering/skyx/src/SkyX.cpp
  gazebo/rendering/skyx/src/VClouds/Lightning.cpp
  gazebo/rendering/skyx/src/VCloudsManager.cpp
  gazebo/sensors/CameraSensor.cc
  gazebo/sensors/GpuRaySensor.cc
  gazebo/sensors/MultiCameraSensor.cc
  gazebo/server_main.cc
Labels: 11, enhancement

#2836 [Gazebo 9] Added Profiler to gazebo::rendering
  gazebo/common/Profiler.hh
  gazebo/gui/GLWidget.cc
  gazebo/gui/GuiIface.cc
  gazebo/gui/main.cc
  gazebo/rendering/ApplyWrenchVisual.cc
  gazebo/rendering/Camera.cc
  gazebo/rendering/CameraVisual.cc
  gazebo/rendering/ContactVisual.cc
  gazebo/rendering/DynamicLines.cc
  gazebo/rendering/FPSViewController.cc
  gazebo/rendering/GpuLaser.cc
  gazebo/rendering/LaserVisual.cc
  gazebo/rendering/LensFlare.cc
  gazebo/rendering/Light.cc
  gazebo/rendering/MarkerVisual.cc
  gazebo/rendering/Material.cc
  gazebo/rendering/MovableText.cc
  gazebo/rendering/OculusCamera.cc
  gazebo/rendering/RTShaderSystem.cc
  gazebo/rendering/RenderEngine.cc
  gazebo/rendering/Scene.cc
  gazebo/rendering/SonarVisual.cc
  gazebo/rendering/TransmitterVisual.cc
  gazebo/rendering/UserCamera.cc
  gazebo/rendering/VideoVisual.cc
  gazebo/rendering/Visual.cc
  gazebo/rendering/WrenchVisual.cc
  gazebo/rendering/skyx/src/CloudsManager.cpp
  gazebo/rendering/skyx/src/SkyX.cpp
  gazebo/rendering/skyx/src/VClouds/Lightning.cpp
  gazebo/rendering/skyx/src/VCloudsManager.cpp
  gazebo/sensors/CameraSensor.cc
  gazebo/sensors/GpuRaySensor.cc
  gazebo/sensors/MultiCameraSensor.cc
  gazebo/server_main.cc
Labels: 9, enhancement

#2856 Fix gzclient crash when deleting a model that's being manipulated
  gazebo/gui/ModelManipulator.cc
Labels: 9

#2862 SimpleTrackedVehiclePlugin: fix for boost 1.74
  plugins/SimpleTrackedVehiclePlugin.cc
Labels: 11, build, critical

#2865 SimpleTrackedVehiclePlugin: fix for boost 1.74 (gazebo9)
  plugins/SimpleTrackedVehiclePlugin.cc
Labels: 9, build

#2863 Fix physics based sensor update rate in lockstep mode
  Changelog.md
  gazebo/sensors/Sensor.cc
  gazebo/sensors/SensorManager.cc
  test/worlds/laser_hit_strict_rate_test.world
Labels: 9
