Repository osrf/gazebo, pull requests merged in 2020-07, with the labels that each got.

#2786 Fixed else brackets introduced in #2768
  gazebo/rendering/Visual.cc
Labels: 9.0

#2787 Fixed else brackets introduced in #2770
  gazebo/rendering/Visual.cc
Labels: 11

#2751 Fix pkg-config boost entries for Ubuntu Focal (gazebo9)
  CMakeLists.txt
  Changelog.md
Labels: 9

#2734 Fix corruption when a URDF file is included from a SDFormat 1.6 model
  Changelog.md
  gazebo/common/SdfFrameSemantics.cc
  gazebo/common/SdfFrameSemantics.hh
  gazebo/gui/ModelMaker.cc
  gazebo/gui/ModelMakerPrivate.hh
  gazebo/physics/Model.cc
  gazebo/physics/World.cc
  test/models/test_nested_urdf/model_sdf_1_6/model.config
  test/models/test_nested_urdf/model_sdf_1_6/model_sdf_1_6.sdf
  test/models/test_nested_urdf/model_sdf_1_7/model.config
  test/models/test_nested_urdf/model_sdf_1_7/model_sdf_1_7.sdf
  test/models/test_nested_urdf/model_urdf/model.config
  test/models/test_nested_urdf/model_urdf/model_urdf.urdf
  test/regression/2728_gui_spawned_nested_urdf.cc
  test/regression/2728_nested_urdf.cc
  test/regression/CMakeLists.txt
  test/worlds/sdf_1_6_nested_urdf.world
  tools/cpplint.py
  tools/gz.cc
  tools/gz.hh
Labels: 11

#2788 [Gazebo 9] Added test to check collisions equal to zero
  gazebo/rendering/Visual_TEST.cc
  worlds/collision_zero.world
Labels: 9

#2795 [Forwardport Gazebo 11] Added test to check collisions equal to zero (#2788)
  gazebo/rendering/Visual_TEST.cc
  worlds/collision_zero.world
Labels: 11

#2758 Fix compilation with Boost 1.73
  gazebo/gui/model/ModelTreeWidget.cc
Labels: 11

#2769 [backport Gazebo7] Fixed crash when collision size is zero
  gazebo/rendering/Visual.cc
  gazebo/rendering/Visual_TEST.cc
  worlds/collision_zero.world
Labels: 7

#2799 Lockstep small compiler warning fix
  test/integration/laser.cc
Labels: 11

#2776 [Gazebo 11] Added ignition common profiler
  CMakeLists.txt
  gazebo/CMakeLists.txt
  gazebo/Server.cc
  gazebo/common/CMakeLists.txt
  gazebo/common/Event.hh
  gazebo/physics/CMakeLists.txt
  gazebo/physics/World.cc
  gazebo/physics/bullet/BulletPhysics.cc
  gazebo/physics/dart/DARTPhysics.cc
  gazebo/physics/ode/ODEPhysics.cc
  gazebo/physics/simbody/SimbodyPhysics.cc
  gazebo/rendering/CMakeLists.txt
  gazebo/sensors/AltimeterSensor.cc
  gazebo/sensors/CameraSensor.cc
  gazebo/sensors/ContactSensor.cc
  gazebo/sensors/DepthCameraSensor.cc
  gazebo/sensors/ForceTorqueSensor.cc
  gazebo/sensors/GpsSensor.cc
  gazebo/sensors/GpuRaySensor.cc
  gazebo/sensors/ImuSensor.cc
  gazebo/sensors/LogicalCameraSensor.cc
  gazebo/sensors/MagnetometerSensor.cc
  gazebo/sensors/MultiCameraSensor.cc
  gazebo/sensors/RFIDSensor.cc
  gazebo/sensors/RaySensor.cc
  gazebo/sensors/Sensor.cc
  gazebo/sensors/SensorManager.cc
  gazebo/sensors/SonarSensor.cc
  gazebo/sensors/WideAngleCameraSensor.cc
  gazebo/sensors/WirelessReceiver.cc
  plugins/ActorPlugin.cc
  plugins/ActuatorPlugin.cc
  plugins/ArduCopterPlugin.cc
  plugins/BuoyancyPlugin.cc
  plugins/CartDemoPlugin.cc
  plugins/CessnaPlugin.cc
  plugins/DiffDrivePlugin.cc
  plugins/ElevatorPlugin.cc
  plugins/FiducialCameraPlugin.cc
  plugins/FollowerPlugin.cc
  plugins/GimbalSmall2dPlugin.cc
  plugins/GravityCompensationPlugin.cc
  plugins/JointTrajectoryPlugin.cc
  plugins/LiftDragPlugin.cc
  plugins/LinearBatteryPlugin.cc
  plugins/LinkPlot3DPlugin.cc
  plugins/MisalignmentPlugin.cc
  plugins/MudPlugin.cc
  plugins/PlaneDemoPlugin.cc
  plugins/PressurePlugin.cc
  plugins/RandomVelocityPlugin.cc
  plugins/SimpleTrackedVehiclePlugin.cc
  plugins/SkidSteerDrivePlugin.cc
  plugins/TouchPlugin.cc
  plugins/TransporterPlugin.cc
  plugins/VehiclePlugin.cc
  plugins/WheelSlipPlugin.cc
  plugins/WheelTrackedVehiclePlugin.cc
  plugins/WindPlugin.cc
  worlds/profiler.world
Labels: 11

#2802 Fix lockstep world
  test/worlds/camera_strict_rate.world
Labels: 11

#2793 Backport lockstep changes to gazebo9
  gazebo/Server.cc
  gazebo/common/Events.cc
  gazebo/common/Events.hh
  gazebo/gazebo.1.ronn
  gazebo/gazebo.cc
  gazebo/gazebo_main.cc
  gazebo/gzserver.1.ronn
  gazebo/physics/PhysicsIface.cc
  gazebo/physics/PhysicsIface.hh
  gazebo/physics/World.cc
  gazebo/physics/World.hh
  gazebo/physics/WorldPrivate.hh
  gazebo/rendering/RenderingIface.cc
  gazebo/rendering/RenderingIface.hh
  gazebo/rendering/Scene.cc
  gazebo/rendering/Scene.hh
  gazebo/rendering/ScenePrivate.hh
  gazebo/rendering/Visual.cc
  gazebo/rendering/Visual.hh
  gazebo/sensors/CameraSensor.cc
  gazebo/sensors/CameraSensor.hh
  gazebo/sensors/CameraSensorPrivate.hh
  gazebo/sensors/GpuRaySensor.cc
  gazebo/sensors/GpuRaySensor.hh
  gazebo/sensors/GpuRaySensorPrivate.hh
  gazebo/sensors/MultiCameraSensor.cc
  gazebo/sensors/MultiCameraSensor.hh
  gazebo/sensors/MultiCameraSensorPrivate.hh
  gazebo/sensors/Sensor.cc
  gazebo/sensors/Sensor.hh
  gazebo/sensors/SensorManager.cc
  gazebo/sensors/SensorManager.hh
  gazebo/sensors/SensorPrivate.hh
  gazebo/sensors/WideAngleCameraSensor.cc
  test/integration/camera_sensor.cc
  test/integration/contact_sensor.cc
  test/integration/gpu_laser.cc
  test/integration/imu.cc
  test/integration/laser.cc
  test/integration/logical_camera_sensor.cc
  test/integration/multicamera_sensor.cc
  test/integration/transceiver.cc
  test/worlds/camera_strict_rate.world
  test/worlds/contact_strict_rate.world
  test/worlds/gpu_laser_strict_rate.world
  test/worlds/imu_strict_rate_test.world
  test/worlds/laser_hit_strict_rate_test.world
  test/worlds/logical_camera_strict_rate.world
  test/worlds/multicamera_strict_rate_test.world
  test/worlds/transceiver_strict_rate.world
Labels: 9
