Repository osrf/gazebo, pull requests merged in 2020-11, with the labels that each got.

#2877 Support resource files with spaces
  gazebo/Server.cc
  gazebo/common/ColladaLoader.cc
  gazebo/gui/ModelMaker_TEST.cc
  gazebo/gui/ModelMaker_TEST.hh
  gazebo/test/ServerFixture.cc
  test/integration/factory.cc
  test/integration/world.cc
  test/models/testdb/actor with spaces/meshes/skin with spaces.dae
  test/models/testdb/actor with spaces/model.config
  test/models/testdb/actor with spaces/model.sdf
  test/models/testdb/model with spaces/materials/scripts/material with spaces.material
  test/models/testdb/model with spaces/materials/textures/normal with spaces.png
  test/models/testdb/model with spaces/materials/textures/texture with spaces.png
  test/models/testdb/model with spaces/meshes/materialwithoutspaces.mtl
  test/models/testdb/model with spaces/meshes/mesh with spaces.dae
  test/models/testdb/model with spaces/meshes/mesh with spaces.obj
  test/models/testdb/model with spaces/model.config
  test/models/testdb/model with spaces/model.sdf
  test/worlds/world with spaces.world
Labels: 9, testing

#2885 Update TinyOBJLoader to v2.0.0rc8
  Changelog.md
  Migration.md
  deps/tinyobjloader/tiny_obj_loader.h
  gazebo/common/OBJLoader.cc
  test/models/testdb/model with spaces/meshes/material with spaces.mtl
  test/models/testdb/model with spaces/meshes/mesh with spaces.obj
Labels: 9, common, enhancement

#2887 Support platforms in which qwt headers are not installed in a qwt directory
  gazebo/gui/plot/qwt_gazebo.h
Labels: 11

#2882 Warn instead of fail for non-Earth Dem's on 20.04 (#2828)
  gazebo/common/Dem.cc
  gazebo/physics/HeightmapShape.cc
Labels: 11

#2864 Add support to compile the gazebo executable on Windows
  CMakeLists.txt
  cmake/SearchForStuff.cmake
  deps/CMakeLists.txt
  deps/tiny-process-library/CMakeLists.txt
  gazebo/CMakeLists.txt
  gazebo/gazebo_main.cc
Labels: 11

#2878 SearchForStuff: On Apple platforms do not search for uuid library
  cmake/SearchForStuff.cmake
Labels: 11, os::osx

#2889 ⬆️ 9.16.0
  CMakeLists.txt
  Changelog.md
Labels: 9

#2891 ⬆️ 11.3.0
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 11
