Repository osrf/gazebo, pull requests merged in 2020-09, with the labels that each got.

#2765 Accept relative paths in SDF files
  gazebo/common/CMakeLists.txt
  gazebo/common/CommonIface.cc
  gazebo/common/CommonIface.hh
  gazebo/common/CommonIface_TEST.cc
  gazebo/gui/ModelMaker.cc
  gazebo/gui/model/ModelCreator.cc
  gazebo/msgs/msgs.cc
  gazebo/physics/MeshShape.cc
  gazebo/physics/World.cc
  gazebo/rendering/Visual.cc
  test/integration/factory.cc
  test/models/testdb/relative_paths/materials/textures/checker.png
  test/models/testdb/relative_paths/meshes/test.dae
  test/models/testdb/relative_paths/model.config
  test/models/testdb/relative_paths/model.sdf
Labels: 11, migration

#2839 Fix Windows build: filesystem
  gazebo/common/CMakeLists.txt
  gazebo/common/CommonIface.cc
Labels: 11, bug, os::windows

#2840 Fix ogre log test
  media/materials/scripts/gazebo.material
Labels: 9

#2773 Fix Actor collision if loop / auto_start false
  gazebo/physics/Actor.cc
  gazebo/physics/Actor_TEST.cc
  test/worlds/actor_collisions.world
Labels: 11, bug

#2822 [Gazebo 11] Allow gazebo to download models from Fuel in the sdf files
  gazebo/Server.cc
  gazebo/common/CommonIface.cc
  gazebo/common/FuelModelDatabase.cc
  gazebo/common/FuelModelDatabase.hh
  gazebo/gui/InsertModelWidget.cc
  gazebo/rendering/RenderEngine.cc
  test/integration/factory.cc
  worlds/fuel_models.world
Labels: 11, migration

#2781 Set friction params in DARTCollision for dart 6.10
  gazebo/physics/dart/DARTCollision.cc
  gazebo/physics/dart/DARTLink.cc
  gazebo/physics/dart/DARTSurfaceParams.cc
  gazebo/physics/dart/DARTSurfaceParams.hh
  test/integration/physics_friction.cc
  test/worlds/friction_dir_test.world
  test/worlds/friction_dir_test.world.erb
Labels: 10

#2819 [Gazebo 9] Publish performance metrics
  gazebo/msgs/CMakeLists.txt
  gazebo/msgs/performance_metrics.proto
  gazebo/sensors/SensorManager.cc
Labels: 9, enhancement

#2725 Improve transport::Publisher reliability
  gazebo/transport/Publisher.cc
  test/regression/2724_failing_publisher.cc
  test/regression/CMakeLists.txt
Labels: 9

#2849 Profile gzclient
  gazebo/gui/GLWidget.cc
  gazebo/gui/GuiIface.cc
  gazebo/gui/main.cc
  gazebo/rendering/Camera.cc
  gazebo/rendering/RenderEngine.cc
  gazebo/rendering/Scene.cc
  gazebo/rendering/UserCamera.cc
  gazebo/server_main.cc
Labels: 11

#2848 [Forward Port Gazebo 11] Publish performance metrics (#2819)
  gazebo/msgs/CMakeLists.txt
  gazebo/msgs/performance_metrics.proto
  gazebo/sensors/SensorManager.cc
Labels: 11

#2719 Find OGRE correctly in a system with pkg-config but without OGRE .pc files
  cmake/SearchForStuff.cmake
Labels: 11
